### ISSUE TITLE
Random boot timeouts with Virtualbox 6.1

### ISSUE THREAD

**Issue by elguitar** [Seravo/wordpress#159]
Even with the latest `20201205.0.0` vagrant box and the latest wordpress project, sometimes the boot hangs.

The boot timeout seems random.
```shell
vagrant up  # Timeout
# Killed the virtual machine here
vagrant up  # Booted
vagrant halt && vagrant up  # Timeout
# Killed the virtual machine here
vagrant up  # Booted
vagrant halt && vagrant up  # Booted
```

When the virtual machine hangs on boot, it is not possible to shut it down gracefully from VirtualBox or from vagrant.

I have managed to kill it as follows:
```shell
$ ps x | grep wordpress
1749533 ?        Sl     5:03 /usr/lib/virtualbox/VBoxHeadless --comment wordpress_wordpress-box_1607673016009_32999 --startvm 71b97edb-7bb9-4840-8337-6328dde64fea --vrde config
1804544 pts/14   S+     0:00 grep --color=auto wordpress
$ kill -9 1749533
```
After killing, `vagrant up` can be tried again.

Related:
- https://github.com/Seravo/wp-vagrant/commit/6b36249bced3b409f021de192e937bfb8cc858b6
- https://github.com/Seravo/wp-vagrant/issues/65

**Comment by elguitar** [comment]
I worked on this last week. a508b0dbec090233d88fb4092764cb605e81dad8 should fix this, but testing is still ongoing

**Comment by JoosuaKoskinen** [comment]
The commit mentioned has been merged, has anyone still experienced this?

**Comment by Moppa5** [comment]
@JoosuaKoskinen, I haven't experienced any timeouts during the testing now.

**Comment by JoosuaKoskinen** [comment]
Closing as fixed.
